openapi: 3.0.3
info:
  title: Terms Command API
  description: Terms Command API
  version: 1.0.0
paths:
  /terms:
    post:
      summary: Create Terms
      description: Create Terms
      tags:
        - TermsCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTermsRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TermsResponse'

  /terms/{type}:
    patch:
      summary: Update Terms
      description: Update Terms
      tags:
        - TermsCommand
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTermsRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TermsResponse'
    delete:
      summary: Delete Terms
      description: Delete Terms
      tags:
        - TermsCommand
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content

components:
  schemas:
    TermsResponse:
      type: object
      properties:
        termsId:
          type: string
          description: Terms Id
        type:
          type: string
          description: Terms type
        title:
          type: string
          description: Terms title
        content:
          type: string
          description: Terms content
    CreateTermsRequest:
      type: object
      required:
        - type
        - title
        - content
      properties:
        type:
          type: string
          description: Terms type
        title:
          type: string
          description: Terms title
        content:
          type: string
          description: Terms content
    UpdateTermsRequest:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
          description: Terms title
        content:
          type: string
          description: Terms content
