apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-certificate
spec:
  commonName: micro-ecommerce.com
  dnsNames:
    - micro-ecommerce.com
  secretName: selfsigned-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
