repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
  - repo: https://github.com/dustinsand/pre-commit-jvm
    rev: v0.8.0
    hooks:
      - id: ktlint
        args: [ --format ]
      - id: detekt
        args: [ --config, detekt.yml ]
