apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: micro-ecommerce
deploy:
  helm:
    releases:
      - name: cert-manager
        namespace: cert-manager
        createNamespace: true
        chartPath: k8s/infra/cert-manager
        version: 1.11.1
      - name: istio
        namespace: istio-system
        createNamespace: true
        chartPath: k8s/infra/istio
        valuesFiles:
          - k8s/infra/istio/values.yaml
        version: 1.17.2
      - name: istio-ingressgateway
        namespace: istio-ingressgateway
        createNamespace: true
        chartPath: k8s/infra/istio-ingressgateway
        valuesFiles:
          - k8s/infra/istio-ingressgateway/values.yaml
        version: 1.17.2
      - name: keycloak
        namespace: keycloak
        createNamespace: true
        chartPath: k8s/infra/keycloak
        valuesFiles:
          - k8s/infra/keycloak/values.yaml
        version: 14.2.0
      - name: httpbin
        chartPath: k8s/app/httpbin
        version: 1.0.0
