apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS terms;
    CREATE TABLE terms.terms
    (
        id         INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
        terms_id   VARCHAR(255) NOT NULL,
        type       VARCHAR(255) NOT NULL,
        title      TEXT         NOT NULL,
        content    LONGTEXT     NOT NULL,
        version    BIGINT       NOT NULL,
        is_deleted BOOLEAN      NOT NULL DEFAULT FALSE,
        created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
        created_by VARCHAR(255) NOT NULL,
        updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_by VARCHAR(255) NOT NULL
    );
    GRANT ALL PRIVILEGES ON terms.* TO dev@'%';
